### ISSUE TITLE
Accidental breaking change in 0.6.23

### ISSUE THREAD

**Issue by Dirbaio** [winnow-rs/winnow#689]
```rust
type Foo = winnow::Located<&'static str>;
```

Compiles with 0.6.22, fails with 0.6.23:

```
error[E0412]: cannot find type `Located` in crate `winnow`
 --> src/main.rs:1:20
  |
1 | type Foo = winnow::Located<&'static str>;
  |                    ^^^^^^^ not found in `winnow`
  |
help: consider importing this type alias
  |
1 + use winnow::stream::Located;
  |
help: if you import `Located`, refer to it directly
  |
1 - type Foo = winnow::Located<&'static str>;
1 + type Foo = Located<&'static str>;
  |
```

**Comment by morenol** [comment]
got same error

**Comment by andygrove** [comment]
came here to say the same

**Comment by chikko80** [comment]
breaking multiple libraries

**Comment by Exidex** [comment]
accidental left-pad moment, rcodesign is broken because toml_edit is

**Comment by dgherzka** [comment]
this broke `proc-macro-crate` as well

**Comment by quietlychris** [comment]
Temporary workaround is to specify the exact patch number for `winnow` in your `Cargo.toml`

```toml
[dependencies]
winnow = "=0.6.22"
```

**Comment by willbuckner** [comment]
Any workaround for `cargo install`?

```
cargo install diesel_cli@2.2.6 --no-default-features --features postgres --force
```

is failing. Thanks!

**Comment by willbuckner** [comment]
Can the version be yanked from crates.io?

**Comment by andygrove** [comment]
@epage fyi

**Comment by clarkmcc** [comment]
Please yank! Many GHA and local builds are broken for me!

**Comment by claymcleod** [comment]
FYI, I just caught Ed on Zulip, and he has issued a fix: https://github.com/winnow-rs/winnow/pull/691.
